---
title: "BOLD_EDA_part2"
author: "Lorena Malpica 124841"
date: "12 de julio de 2018"
output: html_document
---
Aquí ya solo se está trabajando con los phylum escogidos para casa reino. 

```{r, warning=F, message=F}
library(dplyr)
library(ggplot2)
library(readr)
bold<-read_csv("./BOLD_data_ph.csv")
model_org<-c('Ashbya gossypii', 'Aspergillus nidulans', 'Coprinus cinereus', 'Cryptococcus neoformans', 'Neurospora crassa', 'Saccharomyces cerevisiae', 'Schizophyllum commune', 'Schizosaccharomyces pombe', 'Arabidopsis thaliana', 'Selaginella moellendorffii', 'Brachypodium distachyon', 'Setaria viridis', 'Lotus japonicus', 'Lemna gibba', 'Medicago truncatula', 'Erythranthe guttata', 'Mimulus guttatus', 'Nicotiana benthamiana', 'Oryza sativa', 'Physcomitrella patens', 'Marchantia polymorpha', 'Amphimedon queenslandica',  'Aplysia cornigera', 'Aplysia fasciata', 'Caenorhabditis elegans', 'Drosophila melanogaster',  'Euprymna scolopes', 'Macrostomum lignano', 'Pristionchus pacificus', 'Scathophaga stercoraria', 'Schmidtea mediterranea', 'Felis sylvestris catus', 'Canis lupus familiaris', 'Mesocricetus auratus', 'Cavia porcellus', 'Oryzias latipes', 'Mus musculus', 'Heterocephalus glaber', 'Columba livia domestica', 'Rattus norvegicus', 'Rhesus macaque', 'Xenopus laevis', 'Xenopus tropicalis', 'Danio rerio', 'Taeniopygia guttata', 'Homo sapiens')
bold_original<-bold
bold<-bold[-(which(!(is.na(match(bold$species_name, model_org))))),]


```

```{r}
metazoa<-bold%>%filter(kingdom=="Metazoa")
met_class<-metazoa%>% group_by(phylum_name, class_name) %>% summarise(n())
colnames(met_class)<- c("Phylum", "Class", "Num_seqs")

plant<-bold%>%filter(kingdom=="Viridiplantae")
pla_class<-plant%>%group_by(phylum_name, class_name) %>% summarise(n())
colnames(pla_class)<-c("Phylum", "Class", "Num_seqs")

fungi<-bold%>%filter(kingdom=="Fungi")
fun_class<-fungi%>%group_by(phylum_name, class_name) %>% summarise (n())
colnames(fun_class)<-c("Phylum", "Class", "Num_seqs")

```

Plots por clase:
```{r, warning=F, message=F}
clas_met_plot<-ggplot(data=met_class)+ aes(x=Class, y=Num_seqs, fill=Class) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Metazoa")
clas_pla_plot<-ggplot(data=pla_class)+ aes(x=Class, y=Num_seqs, fill=Class) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Viridiplantae")
clas_fun_plot<-ggplot(data=fun_class)+ aes(x=Class, y=Num_seqs, fill=Class) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Fungi")
```

```{r, warning=F, message=F}
clas_met_plot
clas_pla_plot
clas_fun_plot
```



```{r, warning=F, message=F}
total<-nrow(bold)
latlon_info<-nrow(bold[bold$latlon_info==T,])
estado_info<-nrow(bold[bold$provincestate_info==T,])
region_info<-nrow(bold[bold$region_info==T,])
sector_info<-nrow(bold[bold$sector_info==T,])
exactsite_info<-nrow(bold[bold$exactsite_info==T,])
geo_info<-rbind(total, latlon_info, estado_info, region_info, sector_info, exactsite_info)
geo_info<-cbind(c("Total", "Info. Coordenadas", "Info. estado", "Info. región", "Info. sector", "Info. sitio exacto"), geo_info)
colnames(geo_info)<-c("Informacion", "Num_seqs")
geo_info<-as.data.frame(geo_info)
geo_info$Num_seqs<-as.numeric(geo_info$Num_seqs)
geo_info$Num_seqs<-c(total, latlon_info, estado_info, region_info, sector_info, exactsite_info)
geo_info_plot<-ggplot(data=geo_info)+ aes(x=Informacion, y=Num_seqs, fill=Informacion) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Informacion geográfica disponible")
geo_info_plot

```

#Gráficas de las clases en cada phylum escogido 

```{r}
pla_class
```

```{r}
met_class
```

```{r, warning=F, message=F}
clas_art_plot<-ggplot(data=met_class[which(met_class$Phylum=="Arthropoda"),])+ aes(x=Class, y=Num_seqs, fill=Class) + geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Arthropoda")
clas_chor_plot<-ggplot(data=met_class[which(met_class$Phylum=="Chordata"),])+ aes(x=Class, y=Num_seqs, fill=Class) + geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Chordata")
clas_asc_plot<-ggplot(data=fun_class[which(fun_class$Phylum=="Ascomycota"),]) + aes(x=Class, y=Num_seqs, fill=Class) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Ascomycota")
clas_bas_plot<-ggplot(data=fun_class[which(fun_class$Phylum=="Basidiomycota"),]) + aes(x=Class, y=Num_seqs, fill=Class) +
                 geom_bar(stat="identity")+theme(axis.text.x=element_text(angle=90)) + ggtitle("Num. de secuencias por clase en Basidiomycota")
```

```{r, warning=F, message=F}
clas_art_plot
clas_chor_plot
clas_asc_plot
clas_bas_plot

```


```{r}
write_csv(bold, "BOLD_data_m.csv")
```

Aquí ya solo se está trabajando con los phylum escogidos para cada reino. 

```{r, warning=F, message=F, echo=F}
library(dplyr)
library(ggplot2)
library(readr)
library(magrittr)
bold<-read_csv("./BOLD_data_m.csv")

```


```{r, warning=F, message=F}
#Marcadores BOLD
#Markers dictionary
plant_markersb<-unique(bold[bold$kingdom=="Viridiplantae", 70])
met_markersb<-unique(bold[bold$kingdom=="Metazoa", 70])
fungi_markersb<-unique(bold[bold$kingdom=="Fungi", 70])

bold_metazoa<-bold[bold$kingdom=="Metazoa",]
bold_fungi<-bold[bold$kingdom=="Fungi",]
bold_plant<-bold[bold$kingdom=="Viridiplantae",]

bold_fungi_m<-filter(bold_fungi, grepl('ITS|ITS1|ITS', markercode))
bold_plant_m<-bold_plant[!(is.na(bold_plant$markercode)),]
bold_meta_m<-filter(bold_metazoa, grepl('COI|COX|CYTB', markercode))
```


GRAFICAS BOLD  DE INFO GEOGRAFICA POR MARCADORES 

BOLD
```{r}
#fungi
bold_f_markers_latlon<-bold_fungi_m%>%group_by(markercode, latlon_info)%>% summarise(n())
colnames(bold_f_markers_latlon)<-c("markercode", "latlon_info", "Num_seqs")

bold_f_markers_province<-bold_fungi_m%>%group_by(markercode, provincestate_info)%>% summarise(n())
colnames(bold_f_markers_province)<-c("markercode", "province_info", "Num_seqs")

bold_f_markers_region<-bold_fungi_m%>%group_by(markercode, region_info)%>% summarise(n())
colnames(bold_f_markers_region)<-c("markercode", "region_info", "Num_seqs")

bold_f_markers_sector<-bold_fungi_m%>%group_by(markercode, sector_info)%>% summarise(n())
colnames(bold_f_markers_sector)<-c("markercode", "sector_info", "Num_seqs")

bold_f_markers_site<-bold_fungi_m%>%group_by(markercode, exactsite_info)%>% summarise(n())
colnames(bold_f_markers_site)<-c("markercode", "site_info", "Num_seqs")


fb_latlon_plot<-ggplot(bold_f_markers_latlon, aes(factor(markercode), Num_seqs, fill=latlon_info)) +
 geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + ggtitle("Datos con/sin coordenadas por marcadores Fungi")  + theme(axis.text.x = element_text(angle = 90, hjust = 1))

fb_province_plot<-ggplot(bold_f_markers_province, aes(factor(markercode), Num_seqs, fill=province_info)) + geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + ggtitle("Datos con/sin province por marcadores Fungi")  + theme(axis.text.x = element_text(angle = 90, hjust = 1))

fb_region_plot<-ggplot(bold_f_markers_region, aes(factor(markercode), Num_seqs, fill=region_info)) + geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + ggtitle("Datos con/sin region por marcadores Fungi")  + theme(axis.text.x = element_text(angle = 90, hjust = 1))

fb_sector_plot<-ggplot(bold_f_markers_sector, aes(factor(markercode), Num_seqs, fill=sector_info)) + geom_bar(stat="identity", position = "dodge") + 
  scale_fill_brewer(palette = "Set1") + ggtitle("Datos con/sin sector por marcadores Fungi")  + theme(axis.text.x = element_text(angle = 90, hjust = 1))

#metazoa

bold_m_markers_latlon<-bold_meta_m%>%group_by(markercode, latlon_info)%>% summarise(n())
colnames(bold_m_markers_latlon)<-c("markercode", "latlon_info", "Num_seqs")

bold_m_markers_province<-bold_meta_m%>%group_by(markercode, provincestate_info)%>% summarise(n())
colnames(bold_m_markers_province)<-c("markercode", "province_info", "Num_seqs")

bold_m_markers_region<-bold_meta_m%>%group_by(markercode, region_info)%>% summarise(n())
colnames(bold_m_markers_region)<-c("markercode", "region_info", "Num_seqs")

bold_m_markers_sector<-bold_meta_m%>%group_by(markercode, sector_info)%>% summarise(n())
colnames(bold_m_markers_sector)<-c("markercode", "sector_info", "Num_seqs")

bold_m_markers_site<-bold_meta_m%>%group_by(markercode, exactsite_info)%>% summarise(n())
colnames(bold_m_markers_site)<-c("markercode", "site_info", "Num_seqs")

#plantae

bold_p_markers_latlon<-bold_plant_m%>%group_by(markercode, latlon_info)%>% summarise(n())
colnames(bold_p_markers_latlon)<-c("markercode", "latlon_info", "Num_seqs")

bold_p_markers_province<-bold_plant_m%>%group_by(markercode, provincestate_info)%>% summarise(n())
colnames(bold_p_markers_province)<-c("markercode", "province_info", "Num_seqs")

bold_p_markers_region<-bold_plant_m%>%group_by(markercode, region_info)%>% summarise(n())
colnames(bold_m_markers_region)<-c("markercode", "region_info", "Num_seqs")

bold_p_markers_sector<-bold_plant_m%>%group_by(markercode, sector_info)%>% summarise(n())
colnames(bold_p_markers_sector)<-c("markercode", "sector_info", "Num_seqs")

bold_p_markers_site<-bold_plant_m%>%group_by(markercode, exactsite_info)%>% summarise(n())
colnames(bold_p_markers_site)<-c("markercode", "site_info", "Num_seqs")

```


Dar el formato adecuado a las gráficas para geógrafos :
```{r}
bold_geo<-bold[,c(69,47:59)]
write_tsv(bold_geo, "BOLD_GEO.tsv")


```









