---
title: "README"
author: "Lorena Malpica"
date: "20 de agosto de 2018"
output: html_document
---

##Scripts
1) EDA_bold.R: script básico para explorar y limpiar los datos descargados de BOLD 
2)EDA_bold.Rmd: realiza y explica los pasos para extraer y limpiar los datos, así como la información que se agregó a mano para los reinos que no aparecían en NCBI, escribe el archivo ya con la info de reinos completa. Genera el archivo BOLD_specieslist.csv, que tiene el número de secuencias por especie. Exploración y gráficas de las secuencias que hay por reino y por phylum y la información geográfica que tienen. Finalmente genera los archivos BOLD_data_ph.csv y plants_bold.csv
2) fileprocessing.sh: extrae la lista de phylum (bold_phylum.txt), y de ahí se introduce esa lista en NCBI para recuperar una lista de ids de cada phylum (es una de las colummnas de tax_bold.txt). Despues extrae la columna del puro id (taxid.txt)
3)retrieve_taxbold.sh: usa los ids del archivo taxid.txt y obtiene un archivo tsv que trae la relación de phylum y reinos. 
4)EDA_bold_pt2.Rmd : empieza leyendo el archivo BOLD_data_ph.csv, 
filtra para excluir a los organismos modelo. Hace gráficas para ver el número de secuencias por clase en cada phylum. Gráfica de información geográfica disponible. Filtra los datos a los marcadores que nos interesan (archivo BOLD_data_m.csv)

##Files
1)bold_data.tsv: datos descargados de BOLD para México. 
2)bold_phylum.txt: lista de los nombres de los phylum de BOLD. 
3) tax_bold.txt: archivo que tiene el nombre y el id ncbi de cada phylum de bold. 
4)taxid.txt: lista de ids de NCBI de cada phylum
5)phylumid_kingdom.tsv: archivo con 3 columnas, phylum id, nombre del phylum y reino. 
6)bold_data_complete: archivo de datos de BOLD ya con la información completa de los reinos. 
7)BOLD_specieslist.csv: el número de secuencias por especie. 
8)latlon_bold.tsv : indica por reino cuantas secuencias tienen la información de latitud y longitud. 
9)BOLD_data_ph.csv: Archivo que tiene únicamente los phylum que nos interesan. 
10) plants_bold.csv : archivo con información taxonómica de planta. 
11)BOLD_data_m.csv: archivo ya filtrado para incluir solo los marcadores que nos interesan. 
