
```{r, echo=FALSE}
library(readr)
genbank <- read_csv("../data/genbank/genbank_euk.csv")
infotax_ncbi <- read_csv("../data/genbank/infotax_ncbi.csv")
```

Add taxonomic information from infotax_ncbi, to genbank data frame

First extract ids from genbank. 

```{r, echo=F}
tax_list<-genbank$tax_id
#List of ids for the complete data set genbank
tax_list<-gsub("taxon:", "", tax_list)
genbank$tax_id2<-tax_list

#Add row for sequences that dont have an ncbi taxonomic information id
not_ncbi<-c("not_ncbi", NA, NA, NA, NA, NA, NA, NA, NA)

#Data frame of all the ids with their taxonomic information
infotax_ncbi<-rbind(infotax_ncbi, not_ncbi)

#Match species id from data frame genbank, to data frame of taxonomic information

matched_species<-match(genbank$tax_id2, infotax_ncbi$Tax_id)
matched_species<-as.data.frame(matched_species)


#Assign the NA row to the missing data 
matched_species[which(is.na(matched_species)),]<-nrow(infotax_ncbi)

#The complete taxonomic information data frame is created and joined with the genbank preexisting columns

tax_df<-infotax_ncbi[matched_species$matched_species,]
genbank<-cbind(genbank, tax_df)
genbank<-genbank[-17]

```


Write complete data frame

```{r}
write_csv(genbank, "../data/genbank/genbank_complete.csv")

```

